spring:
  config:
    import: application-secret.yml


logging:
  file:
    path: /home/ubuntu/spring
  level:
    org.hibernate.SQL: debug

management:
  endpoints:
    web:
      exposure:
        include: health