spring:
  config:
    import: application-secret.yml


logging:
  level:
    org.hibernate.SQL: debug
server:
  servlet:
    session:
      tracking-modes: cookie
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health