spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://54.180.119.91:3306/every_auction?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: test
    password: 123456

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:

    properties:
      hibernate:
        format_sql: true

  redis:
    host: 20.200.217.173
    port: 6379

  session:
    store-type: redis

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 652681080793-8ges5dm290r3camtnge2ajncnrfdhla4.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          naver:
            client-id: fd18InKicL_JYbCAPJ9j
            client-secret: khLTD24DKe
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          kakao:
            client-id: bff99cebc95fe6568401fed2b75c655e
            client-secret: ggQmMxmEdxD6h1qw4jTcPaS36yCUhOAR
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    org.hibernate.SQL: debug
server:
  servlet:
    session:
      tracking-modes: cookie
